### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Teicu** [bouligo/cuterecon#1]
Hi,   
  
in mac I encounter these errors. 

Cheers

_pipenv run python qtrecon.py
Traceback (most recent call last):
  File "/Users/admin/cuterecon/qtrecon.py", line 8, in <module>
    from core.controller import Controller
  File "/Users/admin/cuterecon/core/controller.py", line 17, in <module>
    from core.view import View
  File "/Users/admin/cuterecon/core/view.py", line 105
    final_subsection = f'<p style="background-color: black; color: white; font-family: {Config.get()['user_prefs']['monospaced_fonts']};">{final_subsection}</p>'_

**Comment by bouligo** [comment]
Hello, 

Can you retry with the latest release ?

Thanks !

**Comment by bouligo** [comment]
I just checked with QtRecon 1.6 under MacOSX Ventura 13.7.1, and it runs :

![Screenshot_20241114_025422 copie](https://github.com/user-attachments/assets/aae78759-d8bd-4f3e-828c-a7fef2fda2a3)

**Comment by bouligo** [comment]
I was finally able to reproduce the issue with a python < 3.12. Your issue should be fixed with the latest release 1.7.1.
